### ISSUE TITLE
AltStart crashes the server

### ISSUE THREAD

**Issue by MushiShirohime** [Boyos999/Boyos-Tes3mp-Scripts#4]
[2022-03-13 22:24:18] [INFO]: [Script]: Called "OnGUIAction" for AltStart (0)
[2022-03-13 22:24:18] [ERR]: .\server\scripts\menuHelper.lua:444: attempt to index local 'targetObject' (a nil value)
[2022-03-13 22:24:18] [ERR]: [Script]: Server crash from script error!

**Comment by MushiShirohime** [comment]
Crashed for everyone/every character no matter the location selected.

**Comment by Boyos999** [comment]
@AlienJesus can you post a full server log & are you using any other server scripts? I'm unable to replicate the issue on my own setup.

**Comment by MushiShirohime** [comment]
I disabled all other scripts as I didn't even think about them conflicting but the same thing occurred anyway

[tes3mp-server-2022-03-26-13_36_14.log](https://github.com/Boyos999/Boyos-Tes3mp-Scripts/files/8356138/tes3mp-server-2022-03-26-13_36_14.log)

**Comment by Boyos999** [comment]
@AlienJesus Can you check your customScripts.lua and make sure the line where alternate start is included is: `altStart = require("custom.altStart")`

**Comment by MushiShirohime** [comment]
Ahhh I must have missed a character when I copied it the first time... Didn't even cross my mind to check if I copy pasted it in right or not.
It's working now! Thanks for your time!
